name: Ruby

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Install dependencies
      run: |
        bundle install
    - name: Precompile
      run: |
        bundle exec rake assets:precompile
    - name: Run tests
      run: |
        bundle exec rake test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ror-test-akaru"
          heroku_email: "danerick.galera@gmail.com"